### ISSUE TITLE
Personal changes for M+

### ISSUE THREAD

**Issue by yongri0** [gegenschall/LootSpecManager#1]
Hello, I like this plugin very much, but its M+ has errors.Because the moment the boss is defeated, loot has been determined.I made a simple modification.

/LootSpecManager/LootSpecManager.lua  line152-168

--M+
function events:CHALLENGE_MODE_START(mapID)
  if set_spec(LTSM_API:get_mythicplus_spec(mapID)) then
    print("大米开始，拾取已变更")--means M+ start,spec change
  end
end

--[[function events:CHALLENGE_MODE_COMPLETED()
  print("大米已完成，改回默认拾取。")--means M+ finish,spec default
  set_spec(LTSM_API:get_default_spec())
end]]--not necessary

/LootSpecManager/Gui.lua Add to the end

--buttom
local journalRestoreButton = CreateFrame("Button", "EncounterJournalEncounterFrameInfoCreatureButton1LSSRestoreButton",UIParent,"UIPanelButtonTemplate")
local f = CreateFrame("frame", nil, UIParent, BackdropTemplateMixin and "BackdropTemplate")
local loadframe = CreateFrame("frame")

loadframe:RegisterEvent("ADDON_LOADED")
loadframe:SetScript("OnEvent",function(self,event,addon)
  if(addon == "Blizzard_EncounterJournal") then
    journalRestoreButton:SetWidth(80)
    journalRestoreButton:SetHeight(20)
    journalRestoreButton:SetText("LTSM>>")
    journalRestoreButton:SetParent(EncounterJournal)
    journalRestoreButton:ClearAllPoints()
    journalRestoreButton:SetPoint("TOPRIGHT",EncounterJournal,"TOPRIGHT",-20,0)
    end
end)

journalRestoreButton:SetScript("OnClick",function(self)
  LTSM_GUI.frame:Show()
end)
 

My English is very poor, I hope you can understand what I mean.thx,LOL.

**Comment by gegenschall** [comment]
Thanks for the issue. I've added part of your changeset and released a Beta version. Please let me know if it works.

The button I did not yet add because I'm working on a complete UI overhaul anyways.
